"""
Cross-lingual artist alias mapping and normalization for Apple Music matching.
Handles English, Romanized, Pinyin, and localized alias variations between
streaming platforms (NetEase, QQ Music, Spotify) and Apple Music regional catalogs.
"""

from typing import Dict, List, Optional, Set
import re

# Curated bidirectional alias groups:
# All names in a group are treated as equivalent representations of the same artist.
ARTIST_GROUPS: List[Set[str]] = [
    # Top Chinese Pop / Mandopop / Cantopop
    {"周华健", "wakin chau", "emil wakin chau", "emil chau", "zhou huajian"},
    {"陈奕迅", "eason chan", "chan eason", "chen yixun"},
    {"周杰伦", "jay chou", "chou jay", "zhou jielun"},
    {"张韶涵", "angela chang", "angela zhang", "zhang shaohan"},
    {"许嵩", "vae xu", "vae", "xu song"},
    {"林俊杰", "jj lin", "lin junjie"},
    {"汪苏泷", "silence wang", "wang sulong"},
    {"徐良", "xul", "xu liang"},
    {"周深", "charlie zhou", "zhou shen"},
    {"张碧晨", "diamond zhang", "zhang bichen"},
    {"袁娅维", "tia ray", "yuan yawei"},
    {"单依纯", "shan yichun"},
    {"胡夏", "fox hu", "hu xia"},
    {"邓紫棋", "g.e.m.", "gem", "tang tsz-kei", "g.e.m. 邓紫棋", "deng ziqi"},
    {"王菲", "faye wong", "shirley wong", "wang fei"},
    {"张学友", "jacky cheung", "cheung jacky", "zhang xueyou"},
    {"刘德华", "andy lau", "lau andy", "liu dehua"},
    {"郭富城", "aaron kwok", "kwok aaron", "guo fucheng"},
    {"黎明", "leon lai", "lai leon", "li ming"},
    {"莫文蔚", "karen mok", "mok karen", "mo wenwei"},
    {"孙燕姿", "stefanie sun", "sun yanzi"},
    {"蔡依林", "jolin tsai", "tsai jolin", "cai yilin"},
    {"陶喆", "david tao", "tao david", "tao zhe"},
    {"王力宏", "leehom wang", "wang leehom", "wang lihong"},
    {"五月天", "mayday"},
    {"苏打绿", "sodagreen", "鱼丁糸", "oaeen"},
    {"薛之谦", "joker xue", "xue zhiqian"},
    {"李荣浩", "ronghao li", "li ronghao"},
    {"毛不易", "buyi mao", "mao buyi"},
    {"华晨宇", "chenyu hua", "hua chenyu"},
    {"张杰", "jason zhang", "zhang jie"},
    {"汪峰", "wang feng"},
    {"朴树", "pu shu"},
    {"许巍", "xu wei"},
    {"梁静茹", "fish leong", "leong fish", "liang jingru"},
    {"田馥甄", "hebe tien", "hebe", "tian fuzhen"},
    {"s.h.e", "she", "s.h.e."},
    {"杨丞琳", "rainie yang", "yang chenglin"},
    {"萧敬腾", "jam hsiao", "hsiao jam", "xiao jingteng"},
    {"潘玮柏", "wilber pan", "pan will", "pan weibo"},
    {"罗志祥", "show lo", "luo zhixiang"},
    {"古巨基", "leo ku", "ku leo", "gu juji"},
    {"容祖儿", "joey yung", "yung joey", "rong zuer"},
    {"杨千嬅", "miriam yeung", "yeung miriam", "yang qianhua"},
    {"谢霆锋", "nicholas tse", "tse nicholas", "xie tingfeng"},
    {"张国荣", "leslie cheung", "cheung leslie", "zhang guorong"},
    {"梅艳芳", "anita mui", "mui anita", "mei yanfang"},
    {"黄家驹", "koma wong", "wong ka kui", "huang jiaju"},
    {"beyond", "beyond乐队"},
    {"张惠妹", "a-mei", "amei", "chang hui-mei", "zhang huimei"},
    {"陈绮贞", "cheer chen", "chen qizhen"},
    {"蔡健雅", "tanya chua", "chua tanya", "cai jianya"},
    {"李宗盛", "jonathan lee", "lee jonathan", "li zongsheng"},
    {"罗大佑", "lo ta-you", "tayou lo", "luo dayou"},
    {"信乐团", "shin"},
    {"告五人", "accusefive"},
    {"草东没有派对", "no party for cao dong"},
    {"落日飞车", "sunset rollercoaster"},
    {"新裤子", "new pants"},
    {"二手玫瑰", "second hand rose"},
    {"万能青年旅店", "omnnipotent youth society"},
    {"房东的猫", "the landlady's cat"},
    {"痛仰乐队", "miserable faith"},
    {"海龟先生", "mr. turtle"},
    {"回春丹", "young drug"},
    {"旅行团乐队", "the lifejourney"},
    {"重塑雕像的权利", "re-tros"},
    {"刺猬", "hedgehog"},
    {"达达乐队", "dada"},
    {"反光镜", "reflector"},
    {"逃跑计划", "escape plan"},
    {"南征北战", "nzbz"},
    {"羽泉", "yu quan"},
    {"动力火车", "power station"},
    {"筷子兄弟", "chopstick brothers"},
    {"凤凰传奇", "phoenix legend"},
    {"筷子兄弟", "chopstick brothers"},
    {"花儿乐队", "the flowers"},
    {"飞儿乐团", "f.i.r.", "fir"},
    {"牛奶咖啡", "milk coffee"},
    {"南拳妈妈", "nan quan mama"},
    {"至上励合", "top combine"},
    {"TFBOYS", "tfboys"},
    {"时代少年团", "teens in times", "tnt"},
    {"火箭少女101", "rocket girls 101"},
    {"硬糖少女303", "bonbon girls 303"},
    {"THE9", "the9"},
    {"INTO1", "into1"},
    {"张靓颖", "jane zhang", "zhang liangying"},
    {"周笔畅", "bibi zhou", "zhou bichang"},
    {"李宇春", "chris lee", "li yuchun"},
    {"郁可唯", "yisa yu", "yu kewei"},
    {"吉克隽逸", "summer jike", "jike junyi"},
    {"谭维维", "sitar tan", "tan weiwei"},
    {"尚雯婕", "laure shang", "shang wenjie"},
    {"吴青峰", "greeny wu", "wu qingfeng"},
    {"徐佳莹", "lala hsu", "hsu lala", "xu jiaying"},
    {"韦礼安", "weibird", "wei li-an", "wei lian"},
    {"卢广仲", "crowd lu", "lu guangzhong"},
    {"林宥嘉", "yoga lin", "lin youjia"},
    {"萧亚轩", "elva hsiao", "hsiao elva", "xiao yaxuan"},
    {"梁汉文", "edmond leung", "liang hanwen"},
    {"许志安", "andy hui", "xu zhian"},
    {"苏永康", "william so", "su yongkang"},
    {"郑中基", "ronald cheng", "zheng zhongji"},
    {"陈小春", "jordan chan", "chen xiaochun"},
    {"郑伊健", "ekin cheng", "zheng yijian"},
    {"张卫健", "dicky cheung", "zhang weijian"},
    {"林子祥", "george lam", "lin zixiang"},
    {"叶倩文", "sally yeh", "ye qianwen"},
    {"谭咏麟", "alan tam", "tan yonglin"},
    {"李克勤", "hacken lee", "li keqin"},
    {"陈百强", "danny chan", "chen baiqiang"},
    {"许冠杰", "sam hui", "xu guanjie"},
    {"关正杰", "michael kwan", "guan zhengjie"},
    {"罗文", "roman tam", "luo wen"},
    {"甄妮", "jenny tseng", "zhen ni"},
    {"徐小凤", "paula tsui", "xu xiaofeng"},
    {"汪明荃", "liza wang", "wang mingquan"},
    {"王杰", "dave wang", "wang jie"},
    {"齐秦", "chyi chin", "qi qin"},
    {"童安格", "angus tung", "tong ange"},
    {"姜育恒", "johnny jiang", "jiang yuheng"},
    {"张雨生", "tom chang", "zhang yusheng"},
    {"张信哲", "jeff chang", "zhang xinzhe"},
    {"任贤齐", "richie jen", "ren xianqi"},
    {"伍佰", "wu bai", "wu bai & china blue", "伍佰 & china blue"},
    {"齐豫", "chyi yu", "qi yu"},
    {"潘越云", "michelle pan", "pan yueyun"},
    {"辛晓琪", "winnie hsin", "xin xiaoqi"},
    {"陈淑桦", "sarah chen", "chen shuhua"},
    {"黄莺莺", "tracy huang", "huang yingying"},
    {"苏芮", "julie sue", "su rui"},
    {"顺子", "shunza"},
    {"戴佩妮", "penny tai", "tai penny", "dai peini"},
    {"温岚", "landy wen", "wen lan"},
    {"范玮琪", "christine fan", "fanfan", "fan weiqi"},
    {"梁咏琪", "gigi leung", "liang yongqi"},
    {"张柏芝", "cecilia cheung", "zhang bozhi"},
    {"钟欣潼", "gillian chung", "ah gil"},
    {"蔡卓妍", "charlene choi", "ah sa"},
    {"Twins", "twins"},
    {"卫兰", "janice vidal", "wei lan"},
    {"薛凯琪", "fiona sit", "xue kaiqi"},
    {"邓丽欣", "stephy tang", "deng lixin"},
    {"吴雨霏", "kary ng", "wu yufei"},
    {"连诗雅", "shiga lin", "lian shiya"},
    {"林二汶", "eman lam", "lin erwen"},
    {"卢凯彤", "ellen loo", "lu kaitong"},
    {"at17", "at 17"},
    {"周国贤", "endy chow", "zhou guoxian"},
    {"方大同", "khalil fong", "fong khalil", "fang datong"},
    {"王菀之", "ivana wong", "wang wanzhi"},
    {"张敬轩", "hins cheung", "cheung hins", "zhang jingxuan"},
    {"蓝奕邦", "pong nan", "lan yibang"},
    {"麦浚龙", "juno mak", "mai junlong"},
    {"侧田", "justin lo", "ce tian"},
    {"刘浩龙", "wilfred lau", "liu haolong"},
    {"洪卓立", "ken hung", "hong zhuoli"},
    {"陈柏宇", "jason chan", "chen baiyu"},
    {"林奕匡", "phil lam", "lin yikuang"},
    {"许廷铿", "alfred hui", "xu tingkeng"},
    {"胡鸿钧", "hubert wu", "hu hongjun"},
    {"吴业坤", "james ng", "wu yekun"},
    {"冯允谦", "jay fung", "feng yunqian"},
    {"江海迦", "aga", "jiang haijia"},
    {"李幸倪", "gin lee", "li xingni"},
    {"陈蕾", "panther chan", "chen lei"},
    {"Serrini", "serrini", "梁嘉茵"},
    {"方皓玟", "charmaine fong", "fang haowen"},
    {"Dear Jane", "dear jane"},
    {"Supper Moment", "supper moment"},
    {"RubberBand", "rubberband"},
    {"ToNick", "tonick"},
    {"KOLOR", "kolor"},
    {"MIRROR", "mirror"},
    {"ERROR", "error"},
    {"COLLAR", "collar"},

    # Virtual & Vocaloid
    {"洛天依", "luotianyi", "luo tianyi"},
    {"言和", "yanhe"},
    {"乐正绫", "yezheng ling", "yuezhenling", "ling yuezheng"},
    {"乐正龙牙", "yuezheng longya"},
    {"徵羽摩柯", "zhiyu moke"},
    {"墨清弦", "mo qingxian"},
    {"初音未来", "hatsune miku", "miku hatsune", "miku"},
    {"镜音双子", "kagamine rin / len", "kagamine rin", "kagamine len"},
    {"巡音流歌", "巡音露卡", "megurine luka"},
    {"GUMI", "gumi", "megpoid"},

    # Japanese Artists
    {"谷泽智文", "谷澤智文", "tomofumi tanizawa", "tanizawa tomofumi", "タニザワトモフミ"},
    {"米津玄师", "米津玄師", "kenshi yonezu", "yonezu kenshi", "hachi", "ハチ"},
    {"椎名林檎", "sheena ringo", "ringo sheena"},
    {"宇多田光", "宇多田ヒカル", "hikaru utada", "utada hikaru"},
    {"LiSA", "lisa", "织部里沙"},
    {"Aimer", "aimer", "エメ"},
    {"YOASOBI", "yoasobi"},
    {"RADWIMPS", "radwimps"},
    {"菅田将晖", "菅田将暉", "masaki suda", "suda masaki"},
    {"星野源", "gen hoshino", "hoshino gen"},
    {"King Gnu", "king gnu"},
    {"Official髭男dism", "official higedandism", "official hige dandism", "higedan"},
    {"Ado", "ado"},
    {"花泽香菜", "花澤香菜", "kana hanazawa", "hanazawa kana"},
    {"水树奈奈", "水樹奈々", "nana mizuki", "mizuki nana"},
    {"坂本真绫", "坂本真綾", "maaya sakamoto"},
    {"泽野弘之", "澤野弘之", "hiroyuki sawano", "sawano hiroyuki"},
    {"梶浦由记", "梶浦由記", "yuki kajiura"},
    {"久石让", "久石讓", "joe hisaishi"},
    {"坂本龙一", "坂本龍一", "ryuichi sakamoto"},
    {"玉置浩二", "koji tamaki"},
    {"中岛美雪", "中島みゆき", "miyuki nakajima"},
    {"中岛美嘉", "中島美嘉", "mika nakashima"},
    {"仓木麻衣", "倉木麻衣", "mai kuraki"},
    {"滨崎步", "浜崎あゆみ", "ayumi hamasaki"},
    {"安室奈美惠", "安室奈美恵", "namie amuro"},
    {"幸田来未", "倖田來未", "kumi koda"},
    {"大冢爱", "大塚愛", "ai otsuka"},
    {"西野加奈", "西野カナ", "kana nishino"},
    {"爱缪", "aimyon", "あいみょん"},
    {"Vaundy", "vaundy"},
    {"藤井风", "藤井風", "fujii kaze", "kaze fujii"},
    {"Eve", "eve"},
    {"Yorushika", "ヨルシカ", "yorushika"},
    {"ZUTOMAYO", "ずっと真夜中でいいのに。", "zutomayo"},
    {"美波", "minami"},
    {"绿黄色社会", "緑黄色社会", "ryokuoushoku shaken"},
    {"ONE OK ROCK", "one ok rock", "oor"},
    {"MAN WITH A MISSION", "man with a mission", "mwam"},
    {"SPYAIR", "spyair"},
    {"back number", "back number"},
    {"BUMP OF CHICKEN", "bump of chicken"},
    {"ASIAN KUNG-FU GENERATION", "asian kung-fu generation", "ajikan"},
    {"L'Arc~en~Ciel", "l'arc-en-ciel", "larc en ciel", "彩虹乐队"},
    {"X JAPAN", "x japan"},
    {"GLAY", "glay"},
    {"LUNA SEA", "luna sea"},

    # Korean Artists (K-Pop)
    {"IU", "iu", "李知恩", "lee ji eun"},
    {"TAEYEON", "taeyeon", "金泰妍", "kim tae-yeon"},
    {"BLACKPINK", "blackpink"},
    {"BTS", "bts", "防弹少年团"},
    {"TWICE", "twice"},
    {"Red Velvet", "red velvet"},
    {"NewJeans", "newjeans"},
    {"IVE", "ive"},
    {"aespa", "aespa"},
    {"LE SSERAFIM", "le sserafim"},
    {"(G)I-DLE", "(g)i-dle", "gidle"},
    {"EXO", "exo"},
    {"SEVENTEEN", "seventeen"},
    {"Stray Kids", "stray kids"},
    {"BIGBANG", "bigbang"},
    {"G-DRAGON", "g-dragon", "gd", "权志龙"},
    {"TAEYANG", "taeyang", "东永裴"},
    {"少女时代", "girls' generation", "snsd"},
    {"2NE1", "2ne1"},
    {"Super Junior", "super junior", "suju"},
    {"SHINee", "shinee"},
    {"东方神起", "tvxq!", "tvxq", "dbsk"},
]

# Build lookup index from normalized alias -> group_id
_ALIAS_TO_GROUP: Dict[str, int] = {}
for gid, group in enumerate(ARTIST_GROUPS):
    for name in group:
        norm = name.lower().strip()
        _ALIAS_TO_GROUP[norm] = gid
        # Also clean punctuation: "e.a.s.o.n" -> "eason"
        p_clean = re.sub(r"[^\w\s]", "", norm).strip()
        if p_clean and p_clean != norm:
            _ALIAS_TO_GROUP[p_clean] = gid


def are_artists_equivalent(a1: str, a2: str) -> bool:
    """
    Check if two artist names are identical or known cross-lingual/romanized aliases.
    """
    if not a1 or not a2:
        return False

    n1 = a1.lower().strip()
    n2 = a2.lower().strip()

    if n1 == n2:
        return True

    # Check clean punctuation
    p1 = re.sub(r"[^\w\s]", "", n1).strip()
    p2 = re.sub(r"[^\w\s]", "", n2).strip()
    if p1 and p1 == p2:
        return True

    # Lookup in alias groups
    g1 = _ALIAS_TO_GROUP.get(n1) or _ALIAS_TO_GROUP.get(p1)
    g2 = _ALIAS_TO_GROUP.get(n2) or _ALIAS_TO_GROUP.get(p2)

    if g1 is not None and g2 is not None and g1 == g2:
        return True

    return False
